USE ZEPTO_SQL_PROJECT;

DROP TABLE IF EXISTS ZEPTO;

CREATE TABLE ZEPTO (
sku_id serial primary key,
category varchar(120),
name varchar(150) not null,
mrp numeric(8,2),
discountpercent numeric(5,2),
availableqauntity integer,
discountedsellingprice numeric(8,2),
weightinGms integer,
outofstock boolean,
quantity integer
);

-- DATA EXPLORATION

-- COUNT OF ROWS
SELECT COUNT(*) FROM ZEPTO;


-- SAMPLE DATA 
SELECT * FROM ZEPTO
LIMIT 10;


-- NULL VALUES
SELECT * FROM ZEPTO 
WHERE NAME IS NULL
OR 
 CATEGORY IS NULL
OR 
 MRP IS NULL
OR 
 DISCOUNTPERCENT IS NULL
OR 
 DISCOUNTEDSELLINGPRICE IS NULL
OR 
 WEIGHTINGMS IS NULL
OR 
 AVAILABLEQUANTITY IS NULL
OR 
 OUTOFSTOCK IS NULL
OR 
 QUANTITY IS NULL;


-- DIFFERENT PRODUCT CATGEORIES
SELECT DISTINCT CATEGORY 
FROM ZEPTO 
ORDER BY CATEGORY;


-- PRODUCTS IN STOCK VS OUT OF STOCK
SELECT OUTOFSTOCK,COUNT(*)
FROM ZEPTO 
GROUP BY OUTOFSTOCK;

-- PRODUCT NAMES PRESENT MULTIPLE TIMES
SELECT NAME,COUNT(*) AS "NUMBER OF SKUs"
FROM ZEPTO 
GROUP BY name 
HAVING COUNT(*)>1
ORDER BY COUNT(*) DESC;

-- DATA CLEANING

-- PRODUCTS WITH PRICE = 0
SELECT * FROM ZEPTO 
WHERE MRP = 0 OR DISCOUNTEDSELLINGPRICE = 0;

DELETE FROM ZEPTO
WHERE MRP = 0;


-- CONVERT PAISE TO RUPEES
UPDATE ZEPTO
SET MRP = MRP / 100.0,
DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE / 100.0;
 
SELECT MRP,DISCOUNTEDSELLINGPRICE FROM ZEPTO;

-- Q1. FIND THE TOP 10 BEST VALUE PRODUCTS BASED ON DISCOUNT PERCENT
SELECT DISTINCT NAME,MRP,DISCOUNTPERCENT
FROM ZEPTO 
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;

-- Q2. WHAT ARE THE PRODUCTS WITH HIGH MRP BUT OUT OF STOCK
SELECT DISTINCT NAME,MRP
FROM ZEPTO 
WHERE OUTOFSTOCK = "TRUE" AND MRP >300
ORDER BY MRP DESC;

-- Q3. CALCULATE ESTIMATED REVENUE FOR EACH CATEGORY
SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE;

-- Q4. FIND ALL PRODUCTS WHERE MRP IS GREATER THAN 500 AND DISCOUNT IS LESS THAN 10%
SELECT DISTINCT NAME,MRP,DISCOUNTPERCENT
FROM ZEPTO
WHERE MRP>500 AND DISCOUNTPERCENT <10
ORDER BY MRP DESC,DISCOUNTPERCENT DESC;


-- Q5. IDENTIFY THE TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENT
SELECT CATEGORY,ROUND(AVG(DISCOUNTPERCENT),2) AS HIGHEST_AVG_DISCOUNT_PERCENT
FROM  ZEPTO
GROUP BY CATEGORY
ORDER BY HIGHEST_AVG_DISCOUNT_PERCENT DESC 
LIMIT 5;
 
 
 -- Q6.FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100g AND SORT BY BEST VALUE 
SELECT DISTINCT NAME,DISCOUNTEDSELLINGPRICE,WEIGHTINGMS,
ROUND(DISCOUNTEDSELLINGPRICE/WEIGHTINGMS,2) AS PRICE_PER_GRAM
FROM ZEPTO 
WHERE WEIGHTINGMS >= 100
ORDER BY PRICE_PER_GRAM ASC;


-- Q7.GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW,MEDIUM,BULK.
SELECT DISTINCT NAME,WEIGHTINGMS,
CASE WHEN WEIGHTINGMS < 1000 THEN "LOW"
	 WHEN WEIGHTINGMS < 5000 THEN "MEDIUM"
	 ELSE "BULK"
END AS WIEGHT_CATEGORY
FROM ZEPTO;


-- Q8. WHAT IS THE TOTAL INVENTORY WEIGHT PER CATEGORY
SELECT CATEGORY,
SUM(WEIGHTINGMS * AVAILABLEQUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO 
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT;
  